[tool.poetry]
name = "collections_client-col-344"
version = "0.1.0"
description = ""
authors = ["@yermakhan.serikbayev <yermkahan.serikbayev@nu.edu.kz>"]

[tool.poetry.dependencies]
python = "^3.10"
alembic = "^1.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
