"""Create PortfolioHistory

Revision ID: c9e6c9fa00d7
Revises: 
Create Date: 2022-07-12 15:13:43.848633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e6c9fa00d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfoliohistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_fio', sa.String(length=255), nullable=True),
    sa.Column('cession_date', sa.DateTime(), nullable=True),
    sa.Column('total_request', sa.Integer(), nullable=True),
    sa.Column('success_request', sa.Integer(), nullable=True),
    sa.Column('fail_request', sa.Integer(), nullable=True),
    sa.Column('error_request', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfoliohistory')
    # ### end Alembic commands ###
